version: "3"
volumes:
  data:
networks: 
  mynet:
    driver: bridge
services:
  database:
    image: mysql:5.7
    container_name: squadra-db
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - "data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: igor
    networks: 
      - mynet

  app:
    image: ambientum/php:7.1-caddy
    container_name: squadra-app
    volumes:
      - ".:/var/www/app"
    ports:
      - "80:8080"
    networks: 
      - mynet

 